title: Julie Grandidge - Yoga Teacher
url: "https://julie-yoga.com"
google_analytics: "UA-143814009-1"
google_site_verification: "MVWi0FXUxoJ5aBJmWZIcTwTncPt5l0WAS9YSYKln75w"

permalink: pretty

exclude:
  - CNAME

sass:
  load_paths:
    - _sass
